In [1]:
import torch
from torch import nn
from torch.autograd import Variable

In [2]:
# we work on 0.4.1
torch.__version__

'0.4.1'

In [6]:
w = torch.Tensor([[1,2,3],[4,5,6]])
v = torch.Tensor([[-5,-67,3],[10,-9,197]])

In [7]:
w

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [8]:
w+v

tensor([[ -4., -65.,   6.],
        [ 14.,  -4., 203.]])

In [9]:
w-v

tensor([[   6.,   69.,    0.],
        [  -6.,   14., -191.]])